### ISSUE TITLE
Self loop nodes

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaTeX/TikzGraphs.jl#35]
Hello, 
Is it possible to draw a node with a self loop? How would one proceed?

I tried the following: 
```julia
using LightGraphs
g = SimpleDiGraph(2)
add_edge!(g, (2, 1))
add_edge!(g, (1,1))
TikzGraphs.plot(g, node_styles=Dict(1=>"loop below"))
``` 

The arrow corresponding to the edge (1,1) seems to be there but is poorly formatted.

![image](https://user-images.githubusercontent.com/11876271/60517097-59381b00-9cdf-11e9-8b15-9a19041d750d.png)

**Comment by mykelk** [comment]
Very close. It should look like this:
![image](https://user-images.githubusercontent.com/6294079/60526775-d5157180-9ca5-11e9-97d1-e94e36cd322b.png)

**Comment by mykelk** [comment]
We might want to update the docs to illustrate this.

**Comment by MaximeBouton** [comment]
Thanks! I can submit a PR with this example
