### ISSUE TITLE
LaTeX error

### ISSUE THREAD

**Issue by leephillips** [JuliaTeX/TikzGraphs.jl#42]
A trivial graph with 

    g = DiGraph(2)
    add_edge!(g, 1, 2)
    t = TikzGraphs.plot(g)
    TikzPictures.save(TEX("tpic"), t)

creates a tex file that produces an error when processed with lualatex (so save(SVG(...)), etc., produce the same error):

    ! Argument of \next has an extra }.                                                                                                    
    <inserted text>                                                                                                                        
    \par                                                                                                                                   
    l.11 \ProvidesFileRCS{pgfsys-luatex.def}                                                                                               

This is with the latest texlive (2021) on Debian 10.

**Comment by mossr** [comment]
I tried with the following and `lualatex` produced the PDF without any problems:
- Windows 10 (MiKTeX 20.7), `lualatex` Version 1.12.0
- Ubuntu 20.04 (TeX Live 2021), `lualatex` Version 1.13.2

Could you post the full `tpic.log` file?

**Comment by leephillips** [comment]
I’ve discovered that this error has nothing to do with TikxGraphs. There’s something wrong with my TeXlive installation. Sorry, and thanks for this great project.

**Comment by mossr** [comment]
Glad you figured it out!
