### ISSUE TITLE
1.2.1 patch to sync up with Graphs.jl?

### ISSUE THREAD

**Issue by RenatoGeh** [JuliaTeX/TikzGraphs.jl#48]
Hi,

Thanks for maintaining the package. I was trying to go through the notebook tutorial [here](https://github.com/JuliaTeX/TikzGraphs.jl/blob/master/doc/TikzGraphs.ipynb) and was getting errors on the most basic example.

Here's the simplest MWE possible:

```julia
using Graphs, TikzGraphs
TikzGraphs.plot(DiGraph(1))
```

Which gave me

```julia
ERROR: MethodError: no method matching plot(::SimpleDiGraph{Int64})
Closest candidates are:
  plot(::Any, ::TikzGraphs.Layouts.Layout) at /home/renatogeh/.julia/packages/TikzGraphs/tob6G/src/TikzGraphs.jl:44
  plot(::Any, ::TikzGraphs.Layouts.Layout, ::Vector{T}; args...) where T<:AbstractString at /home/renatogeh/.julia/packages/TikzGraphs/tob6G/src/TikzGraphs.jl:44
  plot(::Any, ::Vector{T}; args...) where T<:AbstractString at /home/renatogeh/.julia/packages/TikzGraphs/tob6G/src/TikzGraphs.jl:45
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```

With all latest versions:
 - Julia: 1.6.3
 - Graphs: 1.4.1
 - TikzGraphs: 1.2.0

My first guess was that it was not recognizing `SimpleDiGraph{Int64}` as an `AbstractGraph` for some reason. Indeed, if I pass a `Layout` the function goes through fine.

```julia
TikzGraphs.plot(DiGraph(1), Layouts.Spring())
```

But complains about something else.

```julia
ERROR: MethodError: no method matching vertices(::SimpleDiGraph{Int64})
Closest candidates are:
  vertices(::LightGraphs.SimpleGraphs.AbstractSimpleGraph) at /home/renatogeh/.julia/packages/LightGraphs/IgJif/src/SimpleGraphs/SimpleGraphs.jl:58
  vertices(::LightGraphs.AbstractGraph) at /home/renatogeh/.julia/packages/LightGraphs/IgJif/src/interface.jl:181
Stacktrace:
 [1] plot(g::SimpleDiGraph{Int64}, layout::TikzGraphs.Layouts.Spring)
   @ TikzGraphs ~/.julia/packages/TikzGraphs/tob6G/src/TikzGraphs.jl:44
 [2] top-level scope
   @ REPL[2]:1
```

What's weird about this is that `vertices` is calling `LightGraphs`, and not `Graphs.jl`. After some digging around, I found out that the latest version (v1.2.0) of TikzGraphs is not yet synced with the latest docs.

An easy fix would be to simply send out a v1.2.1 patch so that we get the updated `Project.toml`, fixing this issue. This way new users won't get confused for not getting the most basic example running in their machines. What do you think?

Thanks

**Comment by guyvdbroeck** [comment]
I ran into the same issue

**Comment by mykelk** [comment]
I just incremented the minor version (instead of patch) at b6b3ff336480e8b6158db3dab356f6bd75d66e2a and will tag it. As suggested in the current Graphs.jl package readme:

> Following semantic versioning, we suggest a patch release when no graphs or other Graphs.jl-objects can be passed through the API of your package by those depending on it, otherwise consider it a breaking release. "Passed through" entails created outside and consumed inside your package and vice versa.

**Comment by mykelk** [comment]
I'll wait until TagBot tags it before I close it.

**Comment by RenatoGeh** [comment]
Great! Thanks!
